server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: video-service
          uri: lb://video-service
          predicates:
            - Path=/api/videos/**,/api/categories/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**,/api/auth/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
